# -*- coding: utf-8 -*-
"""Exercise_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YNfg22oL8dSpbn4-yJGVVNHkcOLdAHTB
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/Twitter_dataset.csv')

df.columns

df.isnull().sum()

df.fillna(0, inplace=True)
df.isnull()

df['timestamp'] = pd.to_datetime(df['timestamp'])
df.set_index('timestamp', inplace=True)

df.columns

df.dtypes

"""Measures of Central Tendency:"""

#calculate mean,median and mode
mean = df.mean()
print("Mean for each company")
print(mean)

median = df.median()
print("Median for each company")
print(median)

mode = df.mode()
print("Mode for each company")
print(mode)

"""Measures of Dispersion:"""

std_dev = df.std()
print("Standard Deviation for each company")
print(std_dev)

variance = df.var()
print("Variance for each company")
print(variance)

range = df.max() - df.min()
print("Range for each company")
print(range)

df.plot(figsize=(12, 6))
plt.title('Mentions Over Time')
plt.xlabel('Timestamp')
plt.ylabel('Mentions')
plt.show()

# Box Plot
plt.figure(figsize=(10, 6))
sns.boxplot(data=df,showfliers=False)
plt.title('Box Plot of Mentions',fontsize=16)
plt.xlabel('Company',fontsize=12)
plt.ylabel('Mentions',fontsize=12)
plt.tight_layout()
plt.show()